frequency: 30
sensor_timeout: 0.1

two_d_mode: true
publish_tf: true

# FRAME CONFIGURATION
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map   # this matches your static transform world → map

# === WHEEL ODOMETRY ===
odom0: husky_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, false,
               false, false, false]
odom0_differential: false
odom0_relative: true

# === OPTITRACK POSE ===
pose0: natnet_ros/Husky/pose_cov
pose0_config: [true, true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]
pose0_relative: false
