base_local_planner: base_local_planner/TrajectoryPlannerROS
base_global_planner: global_planner/GlobalPlanner

GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.2

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 1.0
  resolution: 0.2
  rolling_window: false
  update_frequency: 2.0
  publish_frequency: 1.0
  footprint: [[-0.9, -0.6], [-0.9, 0.6], [0.9, 0.6], [0.9, -0.6]]
  footprint_padding: 0.02
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  static_layer:
    map_topic: /map
    subscribe_to_updates: false
  inflation_layer:
    inflation_radius: 1.0

local_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 1.0
  resolution: 0.2
  rolling_window: true
  update_frequency: 2.0
  publish_frequency: 1.0
  footprint: [[-0.9, -0.6], [-0.9, 0.6], [0.9, 0.6], [0.9, -0.6]]
  footprint_padding: 0.02
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  static_layer:
    map_topic: /map
    subscribe_to_updates: false
  inflation_layer:
    inflation_radius: 1.0

TrajectoryPlannerROS:
  odom_topic: "/husky_velocity_controller/odom"
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 20
  max_vel_x: 0.5
  min_vel_x: 0.15
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.2
  acc_lim_theta: 0.75
  acc_lim_x: 0.75
  escape_vel: -0.1
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.3
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: true
  dwa: false
