base_global_planner: navfn/NavfnROS
base_local_planner: base_local_planner/TrajectoryPlannerROS

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 50.0
  height: 50.0
  resolution: 0.05
  plugins: []

local_costmap:
  global_frame: map
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  plugins: []

TrajectoryPlannerROS:
  odom_topic: "/husky_velocity_controller/odom"
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 20
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.2
  acc_lim_theta: 0.75
  acc_lim_x: 0.75
  escape_vel: -0.1
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.3
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: true
  dwa: false
